### ISSUE TITLE
Bug#0000000000000001

### ISSUE THREAD

**Issue by sekkit** [sekkit/Fenix#28]
---> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNullException()
   at System.Collections.Concurrent.ConcurrentDictionary`2.ContainsKey(TKey key)
   at Fenix.IdManager.IsClientHost(UInt64 hostId) in Fenix.Runtime\Global\IdManager.cs:line 235
   at Fenix.IdManager.GetHostAddr(UInt64 hostId) in Fenix.Runtime\Global\IdManager.cs:line 247
   at Fenix.IdManager.GetHostAddrByActorId(UInt64 actorId, Boolean isClient) in Fenix.Runtime\Global\IdManager.cs:line 506
   at Fenix.ActorRef.Create(UInt64 toHostId, UInt64 toActorId, Type refType, Actor fromActor, Host fromHost, Boolean isClient, IPEndPoint toPeerEP) in Fenix.Runtime\Actor\ActorRef.cs:line 65
   at Fenix.Global.GetActorRefByName(Type refType, String toActorName, Actor fromActor, Host fromHost) in Fenix.Runtime\Global\Global.cs:line 69
   at Fenix.Global.GetActorRef(Type refType, String actorName, Actor fromActor, Host fromHost) in Fenix.Runtime\Global\Global.cs:line 36
   at Fenix.Actor.GetService[T]() in Fenix.Runtime\Actor\Actor.cs:line 325

**Comment by sekkit** [comment]
currently fixed
